# Generated by Django 6.0.8 on 2026-08-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_remove_transaction_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system_role', models.BooleanField(default=False)),
                ('can_view_all_expenses', models.BooleanField(default=False)),
                ('can_approve_expenses', models.BooleanField(default=False)),
                ('can_allocate_budget', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='EMPLOYEE', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='finance_app.role'),
        ),
    ]
